spring.datasource.url=jdbc:postgresql://localhost:5433/maktada_db
spring.datasource.username=user
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=apimaktaba@gmail.com
spring.mail.password=evngrhfimebykkid
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.web.resources.add-mappings=true
spring.mvc.webjars-path-pattern=/webjars/**